# Generated by Django 2.2 on 2019-12-06 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pvChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('pv_name', models.CharField(max_length=510)),
                ('creator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fist', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_chats',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('biography', models.CharField(blank=True, default=True, max_length=255, null=True)),
                ('firstname', models.CharField(default=None, max_length=30)),
                ('lastname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('text', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('type', models.CharField(max_length=10)),
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('send_date_time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
