# Generated by Django 2.2 on 2019-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_auto_20191206_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvchat',
            name='pv_name',
            field=models.CharField(max_length=510, unique=True),
        ),
    ]
