# Generated by Django 2.2 on 2019-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=0)),
                ('verification_code', models.CharField(max_length=8, unique=True)),
                ('verification_code_expire_time', models.DateTimeField()),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('token', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'c_users',
            },
        ),
    ]
